version: '3.8'

services:
  web:
    build: .
    container_name: sql_webapp
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      # Flask environment settings
      - FLASK_APP=app.py
      - FLASK_ENV=production # Use 'development' for debug mode

# The command to start the Flask application.
# We specify --host=0.0.0.0 to make the server accessible from outside the container.
    command: ["flask", "run", "--host=0.0.0.0"]
